# Generated by Django 5.2.15 on 2026-06-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
