# Generated by Django 5.2.15 on 2026-06-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_player_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
