# Generated by Django 5.2.15 on 2026-06-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='min_normal_trophies',
            field=models.IntegerField(default=750),
        ),
    ]
