# Generated by Django 5.2.15 on 2026-06-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_min_normal_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sync_interval_h',
            field=models.FloatField(default=72.0),
        ),
    ]
