# Generated by Django 5.2.15 on 2026-06-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaBrawlerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate', models.FloatField()),
                ('pick_rate', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('brawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_stats', to='core.brawler')),
            ],
        ),
        migrations.CreateModel(
            name='MetaMapStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('brawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_map_stats', to='core.brawler')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_stats', to='core.map')),
            ],
            options={
                'unique_together': {('brawler', 'map')},
            },
        ),
        migrations.CreateModel(
            name='MetaMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate_a', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('brawler_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_matchups_as_a', to='core.brawler')),
                ('brawler_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_matchups_as_b', to='core.brawler')),
            ],
            options={
                'unique_together': {('brawler_a', 'brawler_b')},
            },
        ),
    ]
