# Generated by Django 5.2.15 on 2026-06-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawlers', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metamapstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metabrawlerstats',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metabrawlerstats',
            name='tier',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='metamapstats',
            name='category',
            field=models.CharField(choices=[('best_pick', 'Best Pick'), ('winner', 'Winner'), ('most_used', 'Most Used'), ('not_recommended', 'Not Recommended')], default='best_pick', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metamapstats',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metamapstats',
            name='pick_rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metamapstats',
            name='tier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='metamapstats',
            name='trophy_range',
            field=models.CharField(default='1000+', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='metamapstats',
            unique_together={('brawler', 'map', 'date', 'trophy_range')},
        ),
    ]
