# Generated by Django 5.2.15 on 2026-06-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('brawler_rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perceptions_as_rival', to='core.brawler')),
                ('my_brawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perceptions_as_mine', to='core.brawler')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perceptions', to='core.player')),
            ],
            options={
                'unique_together': {('player', 'my_brawler', 'brawler_rival')},
            },
        ),
    ]
