# Generated by Django 5.2.15 on 2026-06-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_player_tag'),
        ('drafting', '0001_initial'),
        ('matches', '0004_match_api_match_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perception',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='perception',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perceptions', to='matches.match'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='perception',
            unique_together={('match', 'brawler_rival')},
        ),
    ]
