# Generated by Django 5.2.15 on 2026-06-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.map')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='DraftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('brawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_events', to='core.brawler')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_events', to='matches.match')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
