# Generated by Django 5.2.15 on 2026-06-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_my_brawler'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='draft_type',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
