# Generated by Django 5.2.15 on 2026-06-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_draft_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='api_match_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
