# Generated by Django 5.2.15 on 2026-06-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_api_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_star_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='my_brawler_trophies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
