# Generated by Django 5.2.15 on 2026-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_is_star_player_match_my_brawler_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='series_api_match_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
