# Generated by Django 5.2.15 on 2026-06-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_min_normal_trophies'),
        ('matches', '0006_match_series_api_match_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['player', 'result'], name='matches_mat_player__fc0753_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['player', 'mode'], name='matches_mat_player__14239a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['player', 'my_brawler'], name='matches_mat_player__c93623_idx'),
        ),
    ]
