# Generated by Django 5.2.15 on 2026-06-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmember_is_active_clubmember_left_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='restricted_to_seniors',
            field=models.BooleanField(default=False),
        ),
    ]
