# Generated by Django 5.2.15 on 2026-06-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_forumcategory_restricted_to_seniors'),
        ('core', '0004_player_min_normal_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_replies', to='core.player'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_threads', to='core.player'),
        ),
    ]
