# Generated by Django 5.2.15 on 2026-06-25 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_forumreply_likes_forumthread_is_pinned_and_more'),
        ('core', '0004_player_min_normal_trophies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_senior_pct', models.FloatField(default=25.0, help_text='Max percentage of members that can be senior (0-100)')),
                ('weight_days', models.FloatField(default=1.0, help_text='Weight for days in club in senior score')),
                ('weight_ranked', models.FloatField(default=1.5, help_text='Weight for ranked games played in senior score')),
                ('weight_total', models.FloatField(default=0.5, help_text='Weight for total games played in senior score')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='LinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to='clubs.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to='core.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_link_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player', 'user', 'club')},
            },
        ),
    ]
