# Generated by Django 5.2.15 on 2026-06-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubconfig_linkrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='linkable_roles',
            field=models.JSONField(blank=True, default=list, help_text="Roles that can request link (e.g. ['senior', 'member'])"),
        ),
    ]
